# Generated by Django 3.0.4 on 2020-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(max_length=50)),
                ('cert_detail', models.TextField()),
                ('cert_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
